development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
  host: <%= ENV['OPENSHIFT_DB_HOST'] %>
  username: <%= ENV['OPENSHIFT_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_DB_PASSWORD'] %>
